name: Pages

on:
  push:
    branches:
      - master  # default branch
      
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22x
        uses: actions/setup-node@v4
        with:
          node-version: '22.13.0'
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn run build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
